version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=antifraud_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  api:
    build:
      context: .
      dockerfile: src/AntifraudService.Api/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - postgres
      - kafka
    environment:
      - ConnectionStrings__DefaultConnection=Server=postgres;Port=5432;Database=antifraud_db;User Id=postgres;Password=postgres;
      - Kafka__BootstrapServers=kafka:29092
      - Kafka__Topic=transaction-events
      - ASPNETCORE_ENVIRONMENT=Production

  worker:
    build:
      context: .
      dockerfile: src/AntifraudService.Worker/Dockerfile
    depends_on:
      - postgres
      - kafka
      - api
    environment:
      - ConnectionStrings__DefaultConnection=Server=postgres;Port=5432;Database=antifraud_db;User Id=postgres;Password=postgres;
      - Kafka__BootstrapServers=kafka:29092
      - Kafka__Topic=transaction-events
      - ApiSettings__BaseUrl=http://api
      - DOTNET_ENVIRONMENT=Production

volumes:
  postgres_data: